const models=[{name:'Makita DHP484',brand:'Makita',code:'DHP484'},{name:'DeWalt DCD796',brand:'DeWalt',code:'DCD796'},{name:'Milwaukee M18 FPD3',brand:'Milwaukee',code:'M18 FPD3'}];
const labels=['Modell','Funktion','Slitage','Tillbehör','Ditt bud'];
const wear=['Oanvänt','Lite slitage','Tydligt använt','Mycket slitet'];
const wearCopy=['Inga bruksspår','Några ytliga märken','Flera nötta ytor','Utbredd nötning på flera ytor'];
let state={step:0,model:null,function:null,wear:null,kit:[],kitAnswered:false,battery:null,result:null,accepted:false,declined:false,photo:null,photoName:'',query:''};
const content=document.querySelector('#content'),actions=document.querySelector('#actions');
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function drill(level=0){return `<svg viewBox="0 0 240 220" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"><g stroke="#222226" stroke-width="3" stroke-linejoin="round"><path fill="#222226" d="M12 53h48v44H12zM5 67h8v16H5z"/><rect x="40" y="48" width="31" height="53" rx="9" fill="#454549"/><path fill="#ffca20" d="M68 40h111q21 0 21 20v30q0 21-22 21h-36l15 61h-55l-15-62H67Z"/><path fill="#343438" d="m112 111 17 2 15 57h-33l-14-60Z"/><rect x="93" y="169" width="75" height="18" rx="6" fill="#ffca20"/><rect x="82" y="183" width="96" height="28" rx="6" fill="#222226"/><path d="M174 56h14m-14 10h14m-14 10h14" fill="none" stroke-width="5" stroke-linecap="round"/><path d="M50 56v37M59 56v37" stroke="#77777b" stroke-width="2"/></g>${level>=1?'<g fill="none" stroke="#b7a44e" stroke-width="3" stroke-linecap="round"><path d="m85 58 11 1m7 27 8 1"/></g>':''}${level>=2?'<g fill="#dfce87"><path d="M72 45h40v5H76v13h-5Z"/><path d="m153 95 28-1-5 9h-21Z"/></g><g fill="none" stroke="#a9a9a8" stroke-width="4" stroke-linecap="round"><path d="M90 191h24m-16 10h11m6-61 5 15"/></g><path d="m128 78 12 1" stroke="#b7a44e" stroke-width="3" stroke-linecap="round"/>':''}${level>=3?'<g fill="#dfce87"><path d="M114 43h53v6h-53Z"/><path d="m75 91 20 1 5 10H73Z"/><path d="m136 115 6 24-8-1-6-23Z"/><path d="M98 173h58v7h-58Z"/></g><g stroke="#a9a9a8" stroke-width="5" stroke-linecap="round"><path d="M122 191h46m-50 11h39m-47-70 3 12"/></g><g stroke="#b7a44e" stroke-width="3" stroke-linecap="round"><path d="m112 67 16 1m15 19 12 1m-64-13 9 1"/></g>':''}</svg>`}
function cameraIcon(library=false){return library?'<svg viewBox="0 0 32 32" aria-hidden="true"><rect x="3" y="3" width="26" height="26" rx="3"/><circle cx="11" cy="11" r="3"/><path d="m4 24 9-9 7 7 5-5 4 7"/></svg>':'<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M3 9h6l3-5h8l3 5h6v19H3Z"/><circle cx="16" cy="18" r="6"/></svg>'}
function accessoryIcon(kind){const inside={Batteri:'<path d="M24 24h32v8h8v31H16V32h8Z"/><path d="M20 43h40M34 52h12"/>',Laddare:'<path d="M17 36h39l9 26H13Z"/><path d="M27 36V24h20v12M22 49h26M38 59h9M55 31c16-1 19-10 10-14M63 12v10M69 12v10"/>',Väska:'<rect x="12" y="28" width="56" height="39" rx="5"/><path d="M28 28V17h24v11M12 44h56M24 39v11M56 39v11"/>'};return `<svg class="accessory-icon" viewBox="0 0 80 80" aria-hidden="true" fill="#ffca20" stroke="#222226" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round">${inside[kind]}</svg>`}
function pick(text,desc,selected,attrs,extra=''){return `<button class="pick ${selected?'selected':''}" aria-pressed="${!!selected}" ${attrs}>${extra}<span><strong>${text}</strong>${desc?`<small>${desc}</small>`:''}</span></button>`}
function changeStep(n){state.step=n;state.result=null;state.accepted=false;state.declined=false;render(true)}
function render(focus=false){
 const active=document.activeElement;const restore=['model','function','wear','kit','battery'].find(k=>active?.dataset?.[k]!==undefined);const restoreValue=restore?active.dataset[restore]:null;
 const available=state.result==='model'?0:state.result==='function'?1:state.result==='battery'?3:state.step;
 document.querySelector('#progress').innerHTML=labels.map((x,i)=>`<button class="${state.step===i?'current':i<state.step?'done':''}" ${i>available?'disabled':''} ${state.step===i?'aria-current="step"':''} data-step="${i}">${i+1}. ${x}</button>`).join('');
 document.querySelector('#passport').innerHTML=`<div class="passport"><div class="tool-small">${drill(state.wear??0)}</div><strong>${esc(state.model?.name||'Ditt verktyg')}</strong><p>${state.model?'Modell vald · kan ändras':'Börja med modellskylten.'}</p><dl>${state.function!==null?`<div><dt>Funktion</dt><dd>${['Fungerar','Delvis fungerande','Startar inte','Inte testat'][state.function]}</dd></div>`:''}${state.wear!==null?`<div><dt>Slitage</dt><dd>${wear[state.wear]}</dd></div>`:''}</dl></div>`;
 let html='',valid=false,button='Nästa';
 if(state.step===0){html=`<h2 tabindex="-1">Vilket verktyg säljer du?</h2><p class="intro">Börja med en bild av modellskylten.</p><div class="file-options"><label class="upload camera">${cameraIcon()}<span>Ta en bild</span><input type="file" accept="image/*" capture="environment" aria-label="Ta en bild av modellskylten"></label><label class="upload">${cameraIcon(true)}<span>Välj från bilder</span><input type="file" accept="image/*" aria-label="Välj från bilder"></label></div>${state.photo?`<div class="local-photo"><img class="preview-photo" src="${state.photo}" alt="Din valda modellskylt"><p class="status">${esc(state.photoName)}<br>Bilden är vald. Prototypen kan inte läsa den.</p></div>`:''}<p class="minor">Bilden stannar här. Ingen automatisk bildtolkning i prototypen.</p><div class="demo-models"><p class="field-label">Prova flödet med en exempelmodell</p><div id="model-results" class="grid models"></div></div><details class="model-search-disclosure"><summary>Skriv modellnamnet själv</summary><label class="field-label" for="model-search">Märke eller modell</label><input id="model-search" class="search" type="search" placeholder="Till exempel Makita DHP484" value="${esc(state.query)}" autocomplete="off"></details><button class="link-button" id="unknown">Min modell finns inte med</button>`;valid=!!state.model;}

 if(state.step===1){let opts=[['Fungerar som det ska','Startar och fungerar normalt.','✓'],['Fungerar delvis','Ett eller flera fel.','!'],['Startar inte','Reagerar inte när du provar.','×'],['Inte testat','Funktionen är inte kontrollerad.','?']];html=`<h2 tabindex="-1">Fungerar verktyget?</h2><p class="intro">Vi frågar om funktionen nu. Utseendet kommer i nästa steg.</p><div class="grid function-grid">${opts.map((x,i)=>pick(x[0],x[1],state.function===i,`data-function="${i}"`,`<span class="function-icon" aria-hidden="true">${x[2]}</span>`)).join('')}</div><p class="minor">Prova bara verktyget om det är säkert. Skador och fel ska anges här, inte som slitage.</p>`;valid=state.function!==null;button=state.function>0?'Visa besked':'Nästa';}
 if(state.step===2){html=`<h2 tabindex="-1">Hur slitet ser det ut?</h2><p class="intro">Titta på ytan och kanterna. Alla fyra bilder visar hela verktyg.</p><div class="grid wear-grid">${wear.map((x,i)=>`<button class="pick ${state.wear===i?'selected':''}" data-wear="${i}" aria-pressed="${state.wear===i}">${drill(i)}<strong>${x}</strong><small>${wearCopy[i]}</small><span class="selector" aria-hidden="true"></span></button>`).join('')}</div><details><summary>Så jämför du nivåerna</summary><p>Välj det som bäst motsvarar hela verktyget. Lite slitage är enstaka ytliga märken. Tydligt använt har nötning på flera ställen. Mycket slitet har mer utbredd nötning på både hölje, grepp och bas. Sprickor och trasiga delar räknas som fel, inte bara slitage.</p></details>`;valid=state.wear!==null;}
 if(state.step===3){html=`<h2 tabindex="-1">Vad följer med?</h2><p class="intro">Välj allt som ingår, eller välj bara verktyget.</p><div class="grid kit-grid">${['Batteri','Laddare','Väska'].map(x=>pick(x,state.kit.includes(x)?'✓ Valt':'Välj',state.kit.includes(x),`data-kit="${x}"`,accessoryIcon(x))).join('')}</div><button id="no-kit" class="no-kit pick ${state.kitAnswered&&!state.kit.length?'selected':''}" aria-pressed="${state.kitAnswered&&!state.kit.length}">${state.kitAnswered&&!state.kit.length?'✓ ':''}Inga tillbehör – bara verktyget</button>${state.kit.includes('Batteri')?`<div class="notice"><strong>Hur är batteriets skick?</strong><div class="battery-options">${['Inga kända skador','Skadat / osäkert'].map((x,i)=>`<button data-battery="${i}" aria-pressed="${state.battery===i}" class="${state.battery===i?'selected':''}">${x}</button>`).join('')}</div></div>`:''}<p class="minor">Testbudet avser bara de tillbehör du väljer. Batterimodell och kapacitet behöver identifieras i den färdiga tjänsten.</p>`;valid=state.kitAnswered&&(!state.kit.includes('Batteri')||state.battery!==null);button='Visa mitt pris';}
 if(state.step===4){
 if(state.declined){html='<h2 tabindex="-1">Tack för att du provade.</h2><p>Du har tackat nej i prototypen. Ingen affär har skapats.</p>';}
 else if(state.accepted){html=`<span class="step-done" aria-hidden="true">✓</span><h2 tabindex="-1">Så fortsätter affären.</h2><p class="intro">Du har provat att tacka ja. Här slutar den klickbara prisprototypen.</p><ol><li>Bekräfta säljare och äganderätt.</li><li>Få rätt packnings- och fraktinstruktioner.</li><li>Vi kontrollerar verktyget före utbetalning.</li></ol><p class="notice">Inget avtal, ingen frakt och ingen betalning har skapats.</p>`;}
 else if(state.result){html=`<h2 tabindex="-1">Inget bud just nu</h2><p class="intro">${{model:'Vi behöver identifiera exakt modell för att kunna värdera verktyget.',function:'Det här testflödet lämnar inte automatiska bud när verktyget har fel eller inte är testat.',battery:'Vi lämnar inget automatiskt testbud med ett skadat eller osäkert batteri.'}[state.result]}</p><div class="notice">${state.result==='model'?'Gå tillbaka och prova någon av exempelmodellerna.':state.result==='battery'?'Ta inte bort batteriet ur uppgifterna om du fortfarande tänker skicka med det.':'Ändra bara ditt svar om det inte stämmer. Du behöver inte svara på fler frågor för det här beskedet.'}</div><p class="minor">Detta är ett test av flödet. Inköpsregler för defekta verktyg är ännu inte fastställda.</p>`;}
 else {html=`<div class="offer-header"><div><h2 tabindex="-1">Ditt bud</h2><p class="price">500 kr<small>Demobelopp · ingen verklig värdering</small></p></div>${drill(state.wear)}</div><p class="intro">${esc(state.model.name)} · ${wear[state.wear].toLowerCase()}</p><div class="notice"><strong>Priset gäller om verktyget stämmer med dina uppgifter.</strong><br>Vi kontrollerar modell, funktion och skick när det kommer fram. Om något avviker får du ta ställning till ett nytt bud.</div><details><summary>Dina uppgifter · granska eller ändra</summary><ul class="summary-list">${[[state.model.name,0],['Fungerar som det ska',1],[wear[state.wear],2],[state.kit.join(', ')||'Utan tillbehör',3]].map(([x,i])=>`<li>${esc(x)}<button data-step="${i}">Ändra</button></li>`).join('')}</ul></details>`;}
 }
 content.innerHTML=html;
 actions.innerHTML=state.step<4?`<button class="back" id="back" ${state.step===0?'disabled':''}>← Tillbaka</button><button class="primary" id="next" ${valid?'':'disabled'}>${button} →</button>`:state.accepted||state.declined?`<button class="back" id="restart">Testa ett annat verktyg</button><span class="minor">Prototyp · inga externa åtgärder</span>`:state.result?`<button class="back" id="restart">Börja om</button><button class="primary" id="correct">Ändra mitt svar</button>`:`<button class="back" id="decline">Nej tack</button><button class="primary" id="accept">Prova att tacka ja</button>`;

 if(state.step===0){modelResults();document.querySelector('#model-search').addEventListener('input',e=>{state.query=e.target.value;modelResults()});document.querySelector('#unknown').onclick=()=>{state.result='model';state.step=4;render(true)};content.querySelectorAll('input[type=file]').forEach(i=>i.onchange=()=>{const f=i.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return;if(state.photo)URL.revokeObjectURL(state.photo);state.photo=URL.createObjectURL(f);state.photoName=f.name;state.model=null;render()});}
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>changeStep(Number(b.dataset.step)));
 content.querySelectorAll('[data-function]').forEach(b=>b.onclick=()=>{state.function=Number(b.dataset.function);render()});
 content.querySelectorAll('[data-wear]').forEach(b=>b.onclick=()=>{state.wear=Number(b.dataset.wear);render()});
 content.querySelectorAll('[data-kit]').forEach(b=>b.onclick=()=>{state.kitAnswered=true;let x=b.dataset.kit;state.kit=state.kit.includes(x)?state.kit.filter(v=>v!==x):[...state.kit,x];if(!state.kit.includes('Batteri'))state.battery=null;if(!state.kit.length)state.kitAnswered=false;render()});
 content.querySelectorAll('[data-battery]').forEach(b=>b.onclick=()=>{state.battery=Number(b.dataset.battery);render()});
 document.querySelector('#no-kit')?.addEventListener('click',()=>{state.kit=[];state.kitAnswered=true;state.battery=null;render();document.querySelector('#no-kit')?.focus({preventScroll:true})});
 document.querySelector('#next')?.addEventListener('click',()=>{if(!valid)return;if(state.step===1&&state.function>0){state.result='function';state.step=4;render(true)}else if(state.step===3&&state.kit.includes('Batteri')&&state.battery===1){state.result='battery';state.step=4;render(true)}else changeStep(state.step+1)});
 document.querySelector('#back')?.addEventListener('click',()=>state.step===0?location.assign('../v02/'):changeStep(state.step-1));
 document.querySelector('#correct')?.addEventListener('click',()=>changeStep({model:0,function:1,battery:3}[state.result]));
 document.querySelector('#accept')?.addEventListener('click',()=>{state.accepted=true;render(true)});
 document.querySelector('#decline')?.addEventListener('click',()=>{state.declined=true;render(true)});
 document.querySelector('#restart')?.addEventListener('click',reset);
 if(!focus&&restore){document.querySelector(`[data-${restore}="${CSS.escape(restoreValue)}"]`)?.focus({preventScroll:true})}
 if(focus){content.scrollTop=0;content.querySelector('h2')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
}
function modelResults(){const target=document.querySelector('#model-results');const found=models.filter(m=>m.name.toLowerCase().includes(state.query.trim().toLowerCase()));target.innerHTML=found.length?found.map(m=>`<button class="pick ${state.model?.code===m.code?'selected':''}" data-model="${m.code}" aria-pressed="${state.model?.code===m.code}"><strong>${m.brand}</strong><b>${m.code}</b><small>Exempelmodell</small></button>`).join(''):'<p class="empty">Modellen finns inte i testets tre exempel. Ingen modell gissas.</p>';target.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{state.model=models.find(m=>m.code===b.dataset.model);render()});}
function reset(){if(state.photo)URL.revokeObjectURL(state.photo);state={step:0,model:null,function:null,wear:null,kit:[],kitAnswered:false,battery:null,result:null,accepted:false,declined:false,photo:null,photoName:'',query:''};render(true)}
document.querySelector('#reset').onclick=reset;document.querySelector('#home').onclick=e=>{e.preventDefault();reset()};render();
