let basket=[],editing=null,view="tool",bulkDraft={type:"Privatperson",count:"10",description:""};
const models=[{name:'Makita DHP484',brand:'Makita',code:'DHP484'},{name:'DeWalt DCD796',brand:'DeWalt',code:'DCD796'},{name:'Milwaukee M18 FPD3',brand:'Milwaukee',code:'M18 FPD3'}];
const labels=['Modell','Funktion','Slitage','Tillbehör','Ditt bud'];
const wear=['Oanvänt','Lite slitage','Tydligt använt','Mycket slitet'];
const wearCopy=['Inga bruksspår','Några ytliga märken','Flera nötta ytor','Utbredd nötning på flera ytor'];
let state={step:0,model:null,function:null,wear:null,kit:[],kitAnswered:false,battery:null,result:null,accepted:false,declined:false,photo:null,photoName:'',query:''};
const content=document.querySelector('#content'),actions=document.querySelector('#actions');
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function drill(level=0){return `<img class="tool-illustration" src="assets/flow-wear-${level??0}.png" alt="" width="256" height="256">`}
function cameraIcon(library=false){const art=library?'<rect x="7" y="7" width="22" height="22" rx="4"/><path d="M23 3H7a4 4 0 0 0-4 4v16"/><circle cx="14" cy="14" r="2.3"/><path d="m8 25 7-7 5 5 4-4 5 5"/>':'<path d="M5 9h5l2-4h8l2 4h5a3 3 0 0 1 3 3v13a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V12a3 3 0 0 1 3-3Z"/><circle cx="16" cy="18" r="6"/><path d="M25 13h1"/>';return `<svg viewBox="0 0 32 32" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${art}</svg>`}
function accessoryIcon(kind){const names={Batteri:'battery',Laddare:'charger',Väska:'case'};return `<img class="accessory-icon accessory-illustration" src="assets/flow-${names[kind]}.png" alt="" width="256" height="256">`}
function pick(text,desc,selected,attrs,extra=''){return `<button class="pick ${selected?'selected':''}" aria-pressed="${!!selected}" ${attrs}>${extra}<span><strong>${text}</strong>${desc?`<small>${desc}</small>`:''}</span></button>`}
function changeStep(n){state.step=n;state.result=null;state.accepted=false;state.declined=false;render(true)}
function render(focus=false){
 if(view!=='tool'){renderExtra();return;}
 if(editing!==null&&basket[editing]&&state.step<4)basket[editing].price=0;

 const active=document.activeElement;const restore=['model','function','wear','kit','battery'].find(k=>active?.dataset?.[k]!==undefined);const restoreValue=restore?active.dataset[restore]:null;
 const available=state.result==='model'?0:state.result==='function'?1:state.result==='battery'?3:state.step;
 document.querySelector('#progress').innerHTML=labels.map((x,i)=>`<button class="${state.step===i?'current':i<state.step?'done':''}" ${i>available?'disabled':''} ${state.step===i?'aria-current="step"':''} data-step="${i}">${i+1}. ${x}</button>`).join('');
 document.querySelector('#passport').innerHTML=`<div class="passport"><div class="tool-small">${drill(state.wear??0)}</div><strong>${esc(state.model?.name||'Ditt verktyg')}</strong><p>${state.model?'Modell vald · kan ändras':'Börja med modellskylten.'}</p><dl>${state.function!==null?`<div><dt>Funktion</dt><dd>${['Fungerar','Delvis fungerande','Startar inte','Inte testat'][state.function]}</dd></div>`:''}${state.wear!==null?`<div><dt>Slitage</dt><dd>${wear[state.wear]}</dd></div>`:''}</dl></div>`;
 let html='',valid=false,button='Nästa';
 if(state.step===0){html=`<h2 tabindex="-1">Vilket verktyg säljer du?</h2><p class="intro">Börja med en bild av modellskylten.</p><div class="file-options"><label class="upload camera">${cameraIcon()}<span>Ta en bild</span><input type="file" accept="image/*" capture="environment" aria-label="Ta en bild av modellskylten"></label><label class="upload">${cameraIcon(true)}<span>Välj från bilder</span><input type="file" accept="image/*" aria-label="Välj från bilder"></label></div>${state.photo?`<div class="local-photo"><img class="preview-photo" src="${state.photo}" alt="Din valda modellskylt"><p class="status">${esc(state.photoName)}<br>Bilden är vald. Prototypen kan inte läsa den.</p></div>`:''}<p class="minor">Bilden stannar här. Ingen automatisk bildtolkning i prototypen.</p><div class="demo-models"><p class="field-label">Prova flödet med en exempelmodell</p><div id="model-results" class="grid models"></div></div><details class="model-search-disclosure"><summary>Skriv modellnamnet själv</summary><label class="field-label" for="model-search">Märke eller modell</label><input id="model-search" class="search" type="search" placeholder="Till exempel Makita DHP484" value="${esc(state.query)}" autocomplete="off"></details><button class="link-button" id="unknown">Min modell finns inte med</button>`;valid=!!state.model;}

 if(state.step===1){let opts=[['Fungerar utan problematik','Startar och fungerar normalt.','✓'],['Fungerar delvis / startar inte','Vi köper inte verktyg med fel i starten.','×']];html=`<h2 tabindex="-1">Fungerar verktyget?</h2><p class="intro">Vi frågar om funktionen nu. Utseendet kommer i nästa steg.</p><div class="grid function-grid">${opts.map((x,i)=>pick(x[0],x[1],state.function===i,`data-function="${i}"`,`<span class="function-icon" aria-hidden="true">${x[2]}</span>`)).join('')}</div><p class="minor">Prova bara verktyget om det är säkert. Skador och fel ska anges här, inte som slitage.</p>`;valid=state.function!==null;button=state.function>0?'Visa besked':'Nästa';}
 if(state.step===2){html=`<h2 tabindex="-1">Hur slitet ser det ut?</h2><p class="intro">Titta på ytan och kanterna. Alla fyra bilder visar hela verktyg.</p><div class="grid wear-grid">${wear.map((x,i)=>`<button class="pick ${state.wear===i?'selected':''}" data-wear="${i}" aria-pressed="${state.wear===i}">${drill(i)}<strong>${x}</strong><small>${wearCopy[i]}</small><span class="selector" aria-hidden="true"></span></button>`).join('')}</div><details><summary>Så jämför du nivåerna</summary><p>Välj det som bäst motsvarar hela verktyget. Lite slitage är enstaka ytliga märken. Tydligt använt har nötning på flera ställen. Mycket slitet har mer utbredd nötning på både hölje, grepp och bas. Sprickor och trasiga delar räknas som fel, inte bara slitage.</p></details>`;valid=state.wear!==null;}
 if(state.step===3){html=`<h2 tabindex="-1">Vad följer med?</h2><p class="intro">Välj allt som ingår, eller välj bara verktyget.</p><div class="grid kit-grid">${['Batteri','Laddare','Väska'].map(x=>pick(x,state.kit.includes(x)?'✓ Valt':'Välj',state.kit.includes(x),`data-kit="${x}"`,accessoryIcon(x))).join('')}</div><button id="no-kit" class="no-kit pick ${state.kitAnswered&&!state.kit.length?'selected':''}" aria-pressed="${state.kitAnswered&&!state.kit.length}">${state.kitAnswered&&!state.kit.length?'✓ ':''}Inga tillbehör – bara verktyget</button>${state.kit.includes('Batteri')?`<div class="notice"><strong>Hur är batteriets skick?</strong><div class="battery-options">${['Inga kända skador','Skadat / osäkert'].map((x,i)=>`<button data-battery="${i}" aria-pressed="${state.battery===i}" class="${state.battery===i?'selected':''}">${x}</button>`).join('')}</div></div>`:''}<p class="minor">Testbudet avser bara de tillbehör du väljer. Batterimodell och kapacitet behöver identifieras i den färdiga tjänsten.</p>`;valid=state.kitAnswered&&(!state.kit.includes('Batteri')||state.battery!==null);button='Visa mitt pris';}
 if(state.step===4){
 if(state.declined){html='<h2 tabindex="-1">Tack för att du provade.</h2><p>Du har tackat nej i prototypen. Ingen affär har skapats.</p>';}
 else if(state.accepted){html=`<span class="step-done" aria-hidden="true">✓</span><h2 tabindex="-1">Så fortsätter affären.</h2><p class="intro">Du har provat att tacka ja. Här slutar den klickbara prisprototypen.</p><ol><li>Bekräfta säljare och äganderätt.</li><li>Få rätt packnings- och fraktinstruktioner.</li><li>Vi kontrollerar verktyget före utbetalning.</li></ol><p class="notice">Inget avtal, ingen frakt och ingen betalning har skapats.</p>`;}
 else if(state.result){html=`<h2 tabindex="-1">Inget bud just nu</h2><p class="intro">${{model:'Vi behöver identifiera exakt modell för att kunna värdera verktyget.',function:'Vi köper just nu bara verktyg som fungerar utan problem. Vi tar inte emot verktyg med fel för reparation.',battery:'Vi lämnar inget automatiskt testbud med ett skadat eller osäkert batteri.'}[state.result]}</p><div class="notice">${state.result==='model'?'Gå tillbaka och prova någon av exempelmodellerna.':state.result==='battery'?'Ta inte bort batteriet ur uppgifterna om du fortfarande tänker skicka med det.':'Ändra bara ditt svar om det inte stämmer. Du behöver inte svara på fler frågor för det här beskedet.'}</div><p class="minor">Detta är ett test av flödet. Verktyg med fel ingår inte i inköpet. Övriga sparade verktyg finns kvar.</p>`;}
 else {html=`<div class="offer-header"><div><h2 tabindex="-1">Ditt bud</h2><p class="price">500 kr<small>Demobelopp · ingen verklig värdering</small></p></div>${drill(state.wear)}</div><p class="intro">${esc(state.model.name)} · ${wear[state.wear].toLowerCase()}</p><div class="offer-trust"><strong>Du bestämmer över affären.</strong><p>Kontroll före utbetalning. Ett ändrat bud kräver att du tar ställning igen.</p><a href="./#omdomen">Kundomdömen <span>· platshållare, inga omdömen ännu</span></a></div><div class="notice"><strong>Priset gäller om verktyget stämmer med dina uppgifter.</strong><br>Vi kontrollerar modell, funktion och skick när det kommer fram. Om något avviker får du ta ställning till ett nytt bud.</div><details><summary>Dina uppgifter · granska eller ändra</summary><ul class="summary-list">${[[state.model.name,0],['Fungerar som det ska',1],[wear[state.wear],2],[state.kit.join(', ')||'Utan tillbehör',3]].map(([x,i])=>`<li>${esc(x)}<button data-step="${i}">Ändra</button></li>`).join('')}</ul></details>`;}
 }
 content.innerHTML=html;
 content.insertAdjacentHTML("afterbegin",entryBar());
 actions.innerHTML=state.step<4?`<button class="back" id="back" ${state.step===0?'disabled':''}>← Tillbaka</button><button class="primary" id="next" ${valid?'':'disabled'}>${button} →</button>`:state.accepted||state.declined?`<button class="back" id="restart">Testa ett annat verktyg</button><span class="minor">Prototyp · inga externa åtgärder</span>`:state.result?`<button class="back" id="restart">Börja om</button><button class="primary" id="correct">Ändra mitt svar</button>`:`<button class="back" id="decline">Nej tack</button><button class="primary" id="accept">Prova att tacka ja</button>`;

 if(state.step===0){modelResults();document.querySelector('#model-search').addEventListener('input',e=>{state.query=e.target.value;modelResults()});document.querySelector('#unknown').onclick=()=>{state.result='model';state.step=4;render(true)};content.querySelectorAll('input[type=file]').forEach(i=>i.onchange=()=>{const f=i.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return;if(state.photo)URL.revokeObjectURL(state.photo);state.photo=URL.createObjectURL(f);state.photoName=f.name;state.model=null;render()});}
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>changeStep(Number(b.dataset.step)));
 content.querySelectorAll('[data-function]').forEach(b=>b.onclick=()=>{state.function=Number(b.dataset.function);render()});
 content.querySelectorAll('[data-wear]').forEach(b=>b.onclick=()=>{state.wear=Number(b.dataset.wear);render()});
 content.querySelectorAll('[data-kit]').forEach(b=>b.onclick=()=>{state.kitAnswered=true;let x=b.dataset.kit;state.kit=state.kit.includes(x)?state.kit.filter(v=>v!==x):[...state.kit,x];if(!state.kit.includes('Batteri'))state.battery=null;if(!state.kit.length)state.kitAnswered=false;render()});
 content.querySelectorAll('[data-battery]').forEach(b=>b.onclick=()=>{state.battery=Number(b.dataset.battery);render()});
 document.querySelector('#no-kit')?.addEventListener('click',()=>{state.kit=[];state.kitAnswered=true;state.battery=null;render();document.querySelector('#no-kit')?.focus({preventScroll:true})});
 document.querySelector('#next')?.addEventListener('click',()=>{if(!valid)return;if(state.step===1&&state.function>0){state.result='function';state.step=4;render(true)}else if(state.step===3&&state.kit.includes('Batteri')&&state.battery===1){state.result='battery';state.step=4;render(true)}else changeStep(state.step+1)});
 document.querySelector('#back')?.addEventListener('click',()=>state.step===0?location.assign('versions/v02/'):changeStep(state.step-1));
 document.querySelector('#correct')?.addEventListener('click',()=>changeStep({model:0,function:1,battery:3}[state.result]));
 document.querySelector('#accept')?.addEventListener('click',()=>{saveTool();view='basket';render(true)});
 bindEntry();
 if(state.step===4&&!state.result&&!state.accepted&&!state.declined){document.querySelector('#accept').textContent='Spara verktyget';}

 document.querySelector('#decline')?.addEventListener('click',()=>{state.declined=true;render(true)});
 document.querySelector('#restart')?.addEventListener('click',reset);
 if(!focus&&restore){document.querySelector(`[data-${restore}="${CSS.escape(restoreValue)}"]`)?.focus({preventScroll:true})}
 if(focus){content.scrollTop=0;content.querySelector('h2')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
}
function modelResults(){const target=document.querySelector('#model-results');const found=models.filter(m=>m.name.toLowerCase().includes(state.query.trim().toLowerCase()));target.innerHTML=found.length?found.map(m=>`<button class="pick ${state.model?.code===m.code?'selected':''}" data-model="${m.code}" aria-pressed="${state.model?.code===m.code}"><strong>${m.brand}</strong><b>${m.code}</b><small>Exempelmodell</small></button>`).join(''):'<p class="empty">Modellen finns inte i testets tre exempel. Ingen modell gissas.</p>';target.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{state.model=models.find(m=>m.code===b.dataset.model);render()});}
function reset(){view='tool';editing=null;if(state.photo)URL.revokeObjectURL(state.photo);state={step:0,model:null,function:null,wear:null,kit:[],kitAnswered:false,battery:null,result:null,accepted:false,declined:false,photo:null,photoName:'',query:''};render(true)}

function entryBar(){return `<div class="mode-switch" aria-label="Hur vill du sälja?"><button id="mode-tool" aria-pressed="${view!=='bulk'}">Ett eller flera verktyg</button><button id="mode-bulk" aria-pressed="${view==='bulk'}">Större parti / bulk</button></div><div class="basket-bar"><span>${view==='tool'?'Verktyg '+(editing===null?basket.length+1:editing+1):'Din försäljning'} · privatperson eller företag</span><button id="open-basket">${basket.length} sparade verktyg</button></div>`}
function bindEntry(){document.querySelector('#mode-tool')?.addEventListener('click',()=>{view='tool';render()});document.querySelector('#mode-bulk')?.addEventListener('click',()=>{view='bulk';render()});document.querySelector('#open-basket')?.addEventListener('click',()=>{view='basket';render()})}
function saveTool(){const item={...state,kit:[...state.kit],photo:null,photoName:'',price:500};if(editing===null){basket.push(item);editing=basket.length-1;}else basket[editing]=item;}
function processSteps(){return `<ol class="journey"><li><strong>1. Tacka ja till budet</strong><span>Säljaruppgifter och rätten att sälja behöver bekräftas.</span></li><li><strong>2. Få QR-kod och fraktinstruktioner</strong><span>När försändelsen är godkänd får du rätt instruktioner.</span></li><li><strong>3. Packa och skicka</strong><span>Flera verktyg kan samlas. Antal paket beror på vikt, mått och batterier.</span></li><li><strong>4. Vi kontrollerar</strong><span>Vi jämför modell, funktion, skick och tillbehör med uppgifterna.</span></li><li><strong>5. Du får pengarna</strong><span>Utbetalning efter godkänd kontroll.</span></li></ol>`}
function renderExtra(){document.querySelector('#progress').innerHTML='';let html=entryBar();
 if(view==='bulk'){html+=`<h2>Vill du sälja ett större parti?</h2><p class="intro">Till exempel 10 eller 100 maskiner. Samla ett underlag för hela partiet.</p><label class="field-label">Du säljer som<select id="seller"><option ${bulkDraft.type==='Privatperson'?'selected':''}>Privatperson</option><option ${bulkDraft.type==='Företag'?'selected':''}>Företag</option></select></label><label class="field-label">Ungefär hur många verktyg?<input id="bulk-count" type="number" min="1" max="10000" value="${esc(bulkDraft.count)}"></label><label class="field-label">Vad ingår?<textarea id="bulk-description" rows="4" placeholder="Märken, modeller och skick om du har det.">${esc(bulkDraft.description)}</textarea></label><p class="notice">Prototyp: underlaget laddas ned som text. Ingen förfrågan skickas. Kontaktadress och hantering av partier behöver fastställas.</p>`;actions.innerHTML='<button class="back" id="return-tool">Till verktyget</button><button class="primary" id="download">Ladda ned underlag</button>';}
 else if(view==='done'){html+=`<h2>Så går försäljningen vidare.</h2><p class="notice">Du har provat att tacka ja. Ingen affär, QR-kod eller betalning har skapats.</p>${processSteps()}`;actions.innerHTML='<button class="secondary" id="return-basket">Tillbaka till samlat bud</button>';}
 else {html+=`<h2>Dina verktyg, ett samlat ärende.</h2><p class="intro">${basket.length?basket.length+' verktyg sparade. Du kan lägga till fler innan du går vidare.':'Inga verktyg sparade ännu.'}</p><ul class="basket-list">${basket.map((x,i)=>`<li><div><strong>${esc(x.model.name)}</strong><small>${wear[x.wear]} · ${esc(x.kit.join(', ')||'Utan tillbehör')}</small><b>${x.price?"500 kr · testbud":"Ändras – nytt bud behövs"}</b></div><div><button data-edit="${i}">Ändra</button><button data-remove="${i}">Ta bort</button></div></li>`).join('')}</ul><button class="secondary" id="add-tool">+ Lägg till ett verktyg</button>${basket.length?`<p class="price">${basket.reduce((sum,x)=>sum+x.price,0)} kr<small>Samlat demobelopp · ingen verklig värdering</small></p><p class="notice">Samma ärende, så få paket som möjligt. Fraktupplägget behöver kontrolleras innan QR-kod skapas.</p><details open><summary>Så här fungerar det</summary>${processSteps()}</details><details><summary>Vad behöver vara klart innan en riktig affär?</summary><p>Slutliga villkor för betalningstid, retur, fraktkostnad och avvikande skick återstår att granska. Detta test innebär inget avtal. Ett ändrat bud ska kunden ta ställning till innan affären går vidare.</p></details>`:''}`;actions.innerHTML=`<button class="back" id="return-tool">Till verktyget</button><button class="primary" id="accept-all" ${basket.length&&basket.every(x=>x.price>0)?'':'disabled'}>Prova att tacka ja</button>`;}
 content.innerHTML=html;bindEntry();
 document.querySelector('#return-tool')?.addEventListener('click',()=>{view='tool';render()});
 document.querySelector('#add-tool')?.addEventListener('click',reset);
 document.querySelector('#accept-all')?.addEventListener('click',()=>{if(!basket.length||basket.some(x=>!x.price))return;view='done';render()});
 document.querySelector('#return-basket')?.addEventListener('click',()=>{view='basket';render()});
 content.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=Number(b.dataset.edit);state={...basket[editing],kit:[...basket[editing].kit],step:0};basket[editing].price=0;view='tool';render()});
 content.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.remove);basket.splice(i,1);if(editing===i){editing=null;}else if(editing!==null&&editing>i)editing--;render()});
 const seller=document.querySelector('#seller'),count=document.querySelector('#bulk-count'),desc=document.querySelector('#bulk-description');
 if(seller){seller.onchange=()=>bulkDraft.type=seller.value;count.oninput=()=>bulkDraft.count=count.value;desc.oninput=()=>bulkDraft.description=desc.value;document.querySelector('#download').onclick=()=>{if(!count.reportValidity()||!count.value)return;const text=`ToolDrop – partiunderlag (inte skickat)\nSäljare: ${bulkDraft.type}\nAntal: ${bulkDraft.count}\nInnehåll: ${bulkDraft.description}\n`;const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='tooldrop-partiunderlag.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);document.querySelector('#download').textContent='Underlag klart – inte skickat';};}
 content.querySelector('h2')?.setAttribute('tabindex','-1');content.querySelector('h2')?.focus({preventScroll:true});window.scrollTo(0,0);
}
document.querySelector('#reset').onclick=()=>{if(confirm('Börja om och tömma alla sparade verktyg?')){basket=[];reset()}};document.querySelector('#home').onclick=e=>{e.preventDefault();location.href='./'};if(location.hash==='#bulk')view='bulk';render();
